import { Listing, Conversation, Message } from './types'

export const LISTINGS: Listing[] = [
  {
    id: '1',
    title: '2BHK Modern Flat',
    area: 'Andheri West',
    town: 'Mumbai',
    rent: 32000,
    bedrooms: 2,
    bathrooms: 2,
    floor: '3',
    tags: ['Furnished', 'Pet Friendly', 'Parking'],
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop&auto=format',
    available: 'From Aug 1',
    postedBy: 'Riya Sharma',
    postedByAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&auto=format',
    verified: true,
    description: 'A bright, well-maintained 2BHK in the heart of Andheri West. Recently renovated kitchen, two full bathrooms, dedicated parking spot in the basement. Great connectivity — just 7 minutes from Andheri Metro.',
    ownerName: 'Riya Sharma',
    ownerPhone: '+91 98765 43210',
    street: 'Flat 4B, Sunrise Apartments, MG Road',
    postedByPhone: '+91 98989 76767'
  },
  {
    id: '2',
    title: 'Studio near Tech Park',
    area: 'Whitefield',
    town: 'Bengaluru',
    rent: 18500,
    bedrooms: 1,
    bathrooms: 1,
    floor: 'Ground',
    tags: ['Semi-Furnished', 'WiFi Ready', 'Power Backup'],
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop&auto=format',
    available: 'Immediate',
    postedBy: 'Arjun Nair',
    postedByAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&auto=format',
    verified: true,
    description: 'Compact studio designed for working professionals. Located 2km from ITPL — ideal for anyone at Wipro or TCS campuses. Building has 24/7 security and a rooftop terrace.',
    ownerName: 'Arjun Nair',
    ownerPhone: '+91 98765 43211',
    street: 'Room 201, Green Meadows, Whitefield',
    postedByPhone: '+91 98989 76768'
  },
  {
    id: '3',
    title: 'Spacious 3BHK with Terrace',
    area: 'Banjara Hills',
    town: 'Hyderabad',
    rent: 45000,
    bedrooms: 3,
    bathrooms: 3,
    floor: '1',
    tags: ['Fully Furnished', 'Terrace', 'Gated'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop&auto=format',
    available: 'From Sep 15',
    postedBy: 'Priya Menon',
    postedByAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&auto=format',
    verified: false,
    description: 'Generously sized 3BHK in a premium gated society. Private terrace with city views. Walking distance to Banjara Hills Road No. 12 restaurants and shopping.',
    ownerName: 'Priya Menon',
    ownerPhone: '+91 98765 43212',
    street: 'Villa 12, Palm Grove, Banjara Hills',
    postedByPhone: '+91 98989 76769'
  },
  {
    id: '4',
    title: '1BHK Cozy Apartment',
    area: 'Karol Bagh',
    town: 'New Delhi',
    rent: 22000,
    bedrooms: 1,
    bathrooms: 1,
    floor: '2',
    tags: ['Furnished', 'Metro Nearby'],
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop&auto=format',
    available: 'From Aug 10',
    postedBy: 'Kabir Singh',
    postedByAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&auto=format',
    verified: true,
    description: 'Warm and quiet 1BHK two floors up in a well-maintained building. Karol Bagh Metro is a 4-minute walk. Ground-floor grocery and medical shop in the same lane.',
    ownerName: 'Kabir Singh',
    ownerPhone: '+91 98765 43213',
    street: 'Flat 1A, Shanti Nivas, Karol Bagh',
    postedByPhone: '+91 98989 76770'
  },
  {
    id: '5',
    title: 'Heritage Loft, Ground Floor',
    area: 'Fort',
    town: 'Mumbai',
    rent: 55000,
    bedrooms: 2,
    bathrooms: 1,
    floor: 'Ground',
    tags: ['Heritage', 'Unfurnished', 'High Ceiling'],
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop&auto=format',
    available: 'Immediate',
    postedBy: 'Zara Irani',
    postedByAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&h=80&fit=crop&auto=format',
    verified: true,
    description: 'Rare ground-floor loft in a pre-independence building in Fort. Original wooden floors, 14ft ceilings, and south-facing windows. Perfect for a creative studio or family.',
    ownerName: 'Zara Irani',
    ownerPhone: '+91 98765 43214',
    street: 'Flat 302, Sea View Apartments, Fort',
    postedByPhone: '+91 98989 76771'
  },
]

export const CONVERSATIONS: Conversation[] = [
  {
    id: 'c1',
    name: 'Riya Sharma',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&auto=format',
    lastMsg: 'Can I schedule a visit this Saturday?',
    time: '2m ago',
    unread: 2,
    listing: '2BHK Modern Flat · Mumbai',
  },
  {
    id: 'c2',
    name: 'Arjun Nair',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&auto=format',
    lastMsg: 'Is the parking included in rent?',
    time: '1h ago',
    unread: 0,
    listing: 'Studio near Tech Park · Bengaluru',
  },
  {
    id: 'c3',
    name: 'Priya Menon',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&auto=format',
    lastMsg: 'Sounds good, I will confirm by evening.',
    time: 'Yesterday',
    unread: 0,
    listing: '3BHK with Terrace · Hyderabad',
  },
]

export const MESSAGES: Message[] = [
  { id: 'm1', text: 'Hi! I saw your listing for the 2BHK in Andheri West.', sent: false, time: '10:12 AM' },
  { id: 'm2', text: 'Hello! Yes, it\'s still available. Are you looking to move in soon?', sent: true, time: '10:14 AM' },
  { id: 'm3', text: 'Ideally from 1st August. Can I schedule a visit this Saturday?', sent: false, time: '10:15 AM' },
  { id: 'm4', text: 'Saturday works great! I\'m free between 11 AM and 2 PM.', sent: true, time: '10:18 AM' },
  { id: 'm5', text: 'Perfect. Is the parking spot covered?', sent: false, time: '10:20 AM' },
  { id: 'm6', text: 'Yes, basement covered parking — one spot included in the rent.', sent: true, time: '10:21 AM' },
  { id: 'm7', text: 'Can I schedule a visit this Saturday?', sent: false, time: '10:22 AM' },
]
